package gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

import javafx.scene.image.ImageView;

import javafx.scene.control.TreeView;

public class UpdateOrCreateCategoryController6 {
	@FXML
	private Label lblUpdateOrCreate;
	@FXML
	private Button btnOpslaan;
	@FXML
	private Button btnAnnuleer;
	@FXML
	private Label lblErrorMessage;
	@FXML
	private Label lblKiesSdgs;
	@FXML
	private TreeView treeviewSdgs;
	@FXML
	private ImageView arrow1;
	@FXML
	private ImageView arrow2;
	@FXML
	private Label lblGeselecteerdeSdgs;
	@FXML
	private TreeView treeviewGesSdgs;
	@FXML
	private Button btnRemoveSdGoal;
	@FXML
	private Label lblNaam;
	@FXML
	private TextField txtFNaam;
	@FXML
	private Label lblIcoon;
	@FXML
	private ImageView imgIcoon;
	@FXML
	private Label lblKiesIcoon;
	@FXML
	private ListView listIcoon;

	// Event Listener on Button[#btnRemoveSdGoal].onAction
	@FXML
	public void resetSdgs(ActionEvent event) {
		// TODO Autogenerated
	}
}
